package saga

import (
	"context"
	"encoding/json"
	"errors"
	"time"
)

// State is the lifecycle stage of a durable saga instance.
type State string

const (
	// StatePending — instance enqueued by Start, not yet executing.
	StatePending State = "pending"
	// StateRunning — at least one Forward has begun; CurrentStep is
	// the index of the NEXT Forward to run (so 0 means "no forward
	// has completed", 3 means "steps 0..2 are done").
	StateRunning State = "running"
	// StateCompensating — Forward failed; the executor is now running
	// Compensate on prior steps in reverse order. CurrentStep is the
	// index of the failed step; Compensated lists indices whose
	// rollback has completed.
	StateCompensating State = "compensating"
	// StateCompleted — every Forward returned nil.
	StateCompleted State = "completed"
	// StateFailed — Forward failed AND compensation completed (with
	// or without per-step compensate errors).
	StateFailed State = "failed"
)

// Instance is the persisted state of one durable saga run.
type Instance struct {
	// ID uniquely identifies the instance. Caller-supplied or
	// generated by Start. Use a UUIDv7 for sortable IDs.
	ID string
	// Definition is the saga Definition.Name. The executor looks up
	// the in-memory DurableDefinition by this name when resuming.
	Definition string
	// State is the lifecycle stage.
	State State
	// CurrentStep is the index of the next Forward to run when
	// State==StateRunning, or the failed step's index when
	// State==StateCompensating.
	CurrentStep int
	// Compensated is the indices of steps whose Compensate has
	// already returned (success or failure). Used by Resume to
	// continue compensation past a crash.
	Compensated []int
	// Input is the saga's initial input, JSON-serialised so it
	// survives restart.
	Input json.RawMessage
	// StepResults[i] is step i's Forward output, JSON-serialised.
	// Compensate reads its corresponding result so rollback has the
	// data Forward produced.
	StepResults []json.RawMessage
	// LastError holds a redacted summary of the most recent failure
	// (forward or compensate). It is produced via core/redact.ErrorValue
	// so SDK/payload fragments never land in the durable store. Reset
	// to empty when CurrentStep advances.
	LastError string
	// CreatedAt / UpdatedAt are wall-clock timestamps. Backends
	// populate them; callers should not set them.
	CreatedAt time.Time
	UpdatedAt time.Time
}

// IsTerminal reports whether the instance is in StateCompleted or
// StateFailed — i.e. the saga has finished and Resume should not
// pick it up.
func (i Instance) IsTerminal() bool {
	return i.State == StateCompleted || i.State == StateFailed
}

// StateStore persists [Instance] state. Implementations MUST be safe
// for concurrent use. Backends:
//   - In-memory: [NewMemoryStateStore] (tests / single-process)
//   - Postgres: [data/saga/pgstore].New (production)
type StateStore interface {
	// Put writes (or overwrites) the instance. Atomic per instance:
	// readers see the previous state OR the new state, never a
	// half-write.
	Put(ctx context.Context, inst Instance) error

	// Get returns the instance by ID. Returns ErrInstanceNotFound
	// when absent.
	Get(ctx context.Context, id string) (Instance, error)

	// ListResumable returns instances in non-terminal states that
	// haven't been updated within olderThan (i.e. likely abandoned
	// by a crashed process). Pass 0 to list all non-terminal
	// instances regardless of last-update time.
	ListResumable(ctx context.Context, olderThan time.Duration) ([]Instance, error)

	// Delete removes the instance. Used after a successful
	// completion if the caller doesn't need the audit trail. Returns
	// nil if the instance is already gone.
	Delete(ctx context.Context, id string) error
}

// ErrInstanceNotFound is returned by [StateStore.Get] (and the
// executor) when the requested instance ID is unknown.
var ErrInstanceNotFound = errors.New("saga: instance not found")

// ErrDefinitionNotFound is returned by the executor when a stored
// instance's Definition name does not match any DurableDefinition
// registered with the executor — typically a binary version skew
// (the persisted state references a saga that this build dropped).
var ErrDefinitionNotFound = errors.New("saga: definition not registered with executor")
