package redisstream

import (
	"context"
	"encoding/json"
	"fmt"
	"log/slog"
	"time"

	"github.com/google/uuid"
	"github.com/prometheus/client_golang/prometheus"
	goredis "github.com/redis/go-redis/v9"

	"github.com/bds421/rho-kit/infra/redis"
	"github.com/bds421/rho-kit/observability/promutil"
)

// defaultStreamMaxPayloadSize is the default max payload size for stream messages (1 MiB).
const defaultStreamMaxPayloadSize = 1 << 20 // 1 MiB

// ProducerMetrics holds Prometheus collectors for stream producer monitoring.
type ProducerMetrics struct {
	messagesProduced *prometheus.CounterVec
}

// NewProducerMetrics creates and registers producer metrics with the given registerer.
// If reg is nil, prometheus.DefaultRegisterer is used.
func NewProducerMetrics(reg prometheus.Registerer) *ProducerMetrics {
	if reg == nil {
		reg = prometheus.DefaultRegisterer
	}

	m := &ProducerMetrics{
		messagesProduced: prometheus.NewCounterVec(
			prometheus.CounterOpts{
				Namespace: "redis",
				Subsystem: "stream",
				Name:      "messages_produced_total",
				Help:      "Total messages produced to streams.",
			},
			[]string{"stream"},
		),
	}

	promutil.RegisterCollector(reg, m.messagesProduced)

	return m
}

var defaultProducerMetrics = NewProducerMetrics(nil)

// Producer publishes messages to Redis streams with delivery guarantees.
type Producer struct {
	client goredis.UniversalClient
	logger *slog.Logger

	// maxLen controls stream trimming. 0 means no trimming.
	// Uses approximate trimming (~maxLen) for performance.
	maxLen int64

	// retention controls time-based stream trimming via MINID.
	// Entries older than this duration are trimmed approximately.
	// 0 means no time-based trimming.
	// Mutually exclusive with maxLen — if both are set, maxLen takes precedence.
	retention time.Duration

	// maxPayloadSize is the maximum payload size in bytes. 0 means no limit.
	maxPayloadSize int

	metrics *ProducerMetrics
}

// ProducerOption configures a Producer.
type ProducerOption func(*Producer)

// WithProducerLogger sets the logger for the producer.
func WithProducerLogger(l *slog.Logger) ProducerOption {
	return func(p *Producer) { p.logger = l }
}

// WithMaxStreamLen sets the approximate maximum stream length. Messages
// beyond this limit are trimmed using Redis MAXLEN ~N (approximate trimming
// for better performance). 0 disables trimming. Negative values are ignored.
//
// Mutually exclusive with WithRetention — if both are set, MaxLen takes precedence.
func WithMaxStreamLen(n int64) ProducerOption {
	return func(p *Producer) {
		if n >= 0 {
			p.maxLen = n
		}
	}
}

// WithProducerMaxPayloadSize sets the maximum payload size in bytes.
// Messages with a payload exceeding this limit are rejected at publish time.
// Default is 1 MiB. Set to 0 to disable the limit entirely (use with caution).
// Negative values are ignored.
func WithProducerMaxPayloadSize(n int) ProducerOption {
	return func(p *Producer) {
		if n >= 0 {
			p.maxPayloadSize = n
		}
	}
}

// WithRetention enables time-based stream trimming via Redis MINID ~<id>.
// Entries older than the given duration are approximately trimmed on each
// publish. For example, WithRetention(7 * 24 * time.Hour) keeps roughly
// one week of entries. Values <= 0 are ignored.
//
// Mutually exclusive with WithMaxStreamLen — if both are set, MaxLen takes precedence.
func WithRetention(d time.Duration) ProducerOption {
	return func(p *Producer) {
		if d > 0 {
			p.retention = d
		}
	}
}

// WithProducerRegisterer sets the Prometheus registerer for producer metrics.
// If not set, prometheus.DefaultRegisterer is used.
func WithProducerRegisterer(reg prometheus.Registerer) ProducerOption {
	return func(p *Producer) {
		p.metrics = NewProducerMetrics(reg)
	}
}

// NewProducer creates a producer that writes to Redis streams.
// The default maximum payload size is 1 MiB. Override with
// WithProducerMaxPayloadSize. Set to 0 to disable the limit.
func NewProducer(client goredis.UniversalClient, opts ...ProducerOption) *Producer {
	p := &Producer{
		client:         client,
		logger:         slog.Default(),
		maxPayloadSize: defaultStreamMaxPayloadSize,
		metrics:        defaultProducerMetrics,
	}
	for _, o := range opts {
		o(p)
	}
	return p
}

// Publish writes a message to the given stream. The Redis stream ID is
// auto-generated by the server (using *). Returns the server-assigned ID.
//
// The message is stored as a flat hash:
//
//	id       → UUID v7
//	type     → event type
//	payload  → JSON bytes
//	ts       → RFC3339Nano timestamp
//	headers  → JSON-encoded headers map
func (p *Producer) Publish(ctx context.Context, stream string, msg Message) (string, error) {
	if err := redis.ValidateName(stream, "stream"); err != nil {
		return "", err
	}
	if p.maxPayloadSize > 0 && len(msg.Payload) > p.maxPayloadSize {
		return "", fmt.Errorf("payload size %d exceeds max %d", len(msg.Payload), p.maxPayloadSize)
	}
	args, err := p.buildXAddArgs(stream, msg)
	if err != nil {
		return "", err
	}

	result, err := p.client.XAdd(ctx, args).Result()
	if err != nil {
		return "", fmt.Errorf("xadd %s: %w", stream, err)
	}

	p.metrics.messagesProduced.WithLabelValues(stream).Inc()

	p.logger.Debug("message published to stream",
		"stream", stream,
		"redis_id", result,
		"msg_id", msg.ID,
		"type", msg.Type,
	)

	return result, nil
}

// PublishBatch writes multiple messages to a stream in a single pipeline.
// Returns the server-assigned IDs in the same order as the input messages.
//
// Note: Redis pipelines are not atomic. If the pipeline partially fails,
// some messages may have been written. Callers should treat a pipeline
// error as "unknown state" and use idempotent message IDs for deduplication.
func (p *Producer) PublishBatch(ctx context.Context, stream string, msgs []Message) ([]string, error) {
	if err := redis.ValidateName(stream, "stream"); err != nil {
		return nil, err
	}
	if len(msgs) == 0 {
		return nil, nil
	}

	// Pre-validate all messages before building the pipeline to avoid
	// partially constructing pipeline commands that are then discarded.
	for i, msg := range msgs {
		if p.maxPayloadSize > 0 && len(msg.Payload) > p.maxPayloadSize {
			return nil, fmt.Errorf("message [%d] payload size %d exceeds max %d", i, len(msg.Payload), p.maxPayloadSize)
		}
	}

	pipe := p.client.Pipeline()
	cmds := make([]*goredis.StringCmd, len(msgs))

	for i, msg := range msgs {
		args, err := p.buildXAddArgs(stream, msg)
		if err != nil {
			return nil, fmt.Errorf("message [%d]: %w", i, err)
		}
		cmds[i] = pipe.XAdd(ctx, args)
	}

	if _, err := pipe.Exec(ctx); err != nil {
		return nil, fmt.Errorf("pipeline exec: %w", err)
	}

	ids := make([]string, len(cmds))
	var succeeded int
	for i, cmd := range cmds {
		id, err := cmd.Result()
		if err != nil {
			// Record the messages that did succeed before the failure.
			if succeeded > 0 {
				p.metrics.messagesProduced.WithLabelValues(stream).Add(float64(succeeded))
			}
			return nil, fmt.Errorf("xadd result [%d]: %w", i, err)
		}
		ids[i] = id
		succeeded++
	}

	p.metrics.messagesProduced.WithLabelValues(stream).Add(float64(succeeded))

	return ids, nil
}

// buildXAddArgs prepares a message for XADD, filling in defaults for
// missing ID and timestamp, and marshalling headers.
func (p *Producer) buildXAddArgs(stream string, msg Message) (*goredis.XAddArgs, error) {
	if msg.ID == "" {
		id, err := uuid.NewV7()
		if err != nil {
			return nil, fmt.Errorf("generate message ID: %w", err)
		}
		msg.ID = id.String()
	}
	if msg.Timestamp.IsZero() {
		msg.Timestamp = time.Now().UTC()
	}

	values := map[string]any{
		"id":      msg.ID,
		"type":    msg.Type,
		"payload": string(msg.Payload),
		"ts":      msg.Timestamp.Format(time.RFC3339Nano),
	}

	if len(msg.Headers) > 0 {
		headerBytes, err := json.Marshal(msg.Headers)
		if err != nil {
			return nil, fmt.Errorf("marshal headers: %w", err)
		}
		values["headers"] = string(headerBytes)
	}

	args := &goredis.XAddArgs{
		Stream: stream,
		ID:     "*", // Explicitly request server-generated ID.
		Values: values,
	}

	switch {
	case p.maxLen > 0:
		args.MaxLen = p.maxLen
		args.Approx = true
	case p.retention > 0:
		// Redis stream IDs are "<milliseconds>-<seq>". Using "<ms>-0" as
		// MinID trims all entries with a timestamp before the cutoff.
		cutoff := time.Now().Add(-p.retention).UnixMilli()
		args.MinID = fmt.Sprintf("%d-0", cutoff)
		args.Approx = true
	}

	return args, nil
}
