// Package webhook — implementation.
package webhook

import (
	"bytes"
	"context"
	"errors"
	"fmt"
	"io"
	"log/slog"
	"net/http"
	"strconv"
	"time"

	"github.com/bds421/rho-kit/core/v2/id"
	"github.com/bds421/rho-kit/crypto/v2/signing"
	"github.com/bds421/rho-kit/resilience/v2/retry"
)

// Default header names. Receivers wired with
// [httpx/middleware/signedrequest] expect this triplet.
const (
	DefaultSignatureHeader = "X-Kit-Signature"
	DefaultTimestampHeader = "X-Kit-Timestamp"
	DefaultIDHeader        = "X-Kit-Delivery-Id"
)

// Config configures a [Dispatcher].
type Config struct {
	// HTTPClient is used for every Send. Required. Pass
	// [httpx.NewResilientHTTPClient] for kit-default mTLS-aware
	// transport + per-attempt timeouts.
	HTTPClient *http.Client
	// Signer is the HMAC signer used to mint X-Kit-Signature on
	// every delivery. Required.
	Signer *signing.Signer
	// Secret is the HMAC key. Required.
	Secret signing.Secret
}

// Dispatcher sends signed outbound webhooks. Safe for concurrent use.
type Dispatcher struct {
	cfg             Config
	logger          *slog.Logger
	signatureHeader string
	timestampHeader string
	idHeader        string
	retryPolicy     retry.Policy
}

// Option configures a [Dispatcher].
type Option func(*Dispatcher)

// WithLogger overrides slog.Default().
func WithLogger(l *slog.Logger) Option {
	return func(d *Dispatcher) { d.logger = l }
}

// WithSignatureHeader overrides DefaultSignatureHeader.
func WithSignatureHeader(name string) Option {
	if name == "" {
		panic("webhook: WithSignatureHeader requires non-empty name")
	}
	return func(d *Dispatcher) { d.signatureHeader = name }
}

// WithTimestampHeader overrides DefaultTimestampHeader.
func WithTimestampHeader(name string) Option {
	if name == "" {
		panic("webhook: WithTimestampHeader requires non-empty name")
	}
	return func(d *Dispatcher) { d.timestampHeader = name }
}

// WithIDHeader overrides DefaultIDHeader.
func WithIDHeader(name string) Option {
	if name == "" {
		panic("webhook: WithIDHeader requires non-empty name")
	}
	return func(d *Dispatcher) { d.idHeader = name }
}

// WithRetryPolicy overrides the default retry policy
// ([retry.DefaultPolicy]). Use for tighter or looser retry budgets.
func WithRetryPolicy(p retry.Policy) Option {
	return func(d *Dispatcher) { d.retryPolicy = p }
}

// New constructs a Dispatcher. Validates Config; returns an error
// rather than panicking so callers can surface misconfiguration up to
// startup wiring.
func New(cfg Config, opts ...Option) (*Dispatcher, error) {
	if cfg.HTTPClient == nil {
		return nil, errors.New("webhook: Config.HTTPClient is required")
	}
	if cfg.Signer == nil {
		return nil, errors.New("webhook: Config.Signer is required")
	}
	if len(cfg.Secret) == 0 {
		return nil, errors.New("webhook: Config.Secret is required (non-empty)")
	}
	d := &Dispatcher{
		cfg:             cfg,
		signatureHeader: DefaultSignatureHeader,
		timestampHeader: DefaultTimestampHeader,
		idHeader:        DefaultIDHeader,
		retryPolicy:     retry.DefaultPolicy(),
	}
	for _, opt := range opts {
		if opt == nil {
			return nil, errors.New("webhook: option must not be nil")
		}
		opt(d)
	}
	if d.logger == nil {
		d.logger = slog.Default()
	}
	return d, nil
}

// Delivery is one outbound webhook.
type Delivery struct {
	// URL is the absolute target URL. Required.
	URL string
	// Body is the request body. May be empty; signature still computed.
	Body []byte
	// ContentType is the Content-Type header value. Defaults to
	// "application/json" when empty.
	ContentType string
	// Headers carries additional caller-supplied headers. The kit's
	// signature / timestamp / delivery-id headers are set by Send and
	// take precedence over caller-supplied entries with the same name.
	Headers http.Header
	// DeliveryID is a stable identifier the receiver can use for
	// replay-protection (nonce store). Generated by Send if empty.
	DeliveryID string
}

// Send delivers the webhook synchronously with retry. Returns nil on
// any 2xx response. Retries on transport errors and 5xx; gives up on
// 4xx (the receiver said "your fault — don't retry").
//
// The retry policy supplied via WithRetryPolicy bounds the total
// attempts; ctx cancellation halts the loop immediately.
//
// Each attempt re-signs with a FRESH timestamp so a retry that lands
// minutes after the original Send still sits inside the receiver's
// signing.Verify maxAge window. Signing once outside the loop would
// silently get rejected as "expired signature" past the first 30s
// (signing's default future-skew) on retries with long backoff.
func (d *Dispatcher) Send(ctx context.Context, del Delivery) error {
	if del.URL == "" {
		return errors.New("webhook: Delivery.URL is required")
	}
	if del.DeliveryID == "" {
		del.DeliveryID = id.New()
	}
	if del.ContentType == "" {
		del.ContentType = "application/json"
	}

	return retry.DoWith(ctx, d.retryPolicy, func(ctx context.Context) error {
		signature, timestamp, err := d.cfg.Signer.Sign(d.cfg.Secret, del.Body)
		if err != nil {
			// Signing failures are permanent (programmer bug — bad
			// secret, broken signer). Mark non-retryable.
			return permanent(fmt.Errorf("webhook: sign: %w", err))
		}
		return d.attempt(ctx, del, signature, timestamp)
	}, retry.WithRetryIf(isRetryable))
}

// attempt performs one HTTP delivery. Returns nil on 2xx, a wrapped
// retryable error on 5xx / network failures, and a permanent error
// on 4xx (so the retry policy gives up).
func (d *Dispatcher) attempt(ctx context.Context, del Delivery, signature string, timestamp int64) error {
	req, err := http.NewRequestWithContext(ctx, http.MethodPost, del.URL, bytes.NewReader(del.Body))
	if err != nil {
		return permanent(fmt.Errorf("webhook: build request: %w", err))
	}
	req.Header.Set("Content-Type", del.ContentType)
	for k, vs := range del.Headers {
		for _, v := range vs {
			req.Header.Add(k, v)
		}
	}
	// Kit headers take precedence over caller-supplied headers.
	req.Header.Set(d.signatureHeader, signature)
	req.Header.Set(d.timestampHeader, strconv.FormatInt(timestamp, 10))
	req.Header.Set(d.idHeader, del.DeliveryID)

	resp, err := d.cfg.HTTPClient.Do(req)
	if err != nil {
		return retryable(fmt.Errorf("webhook: do: %w", err))
	}
	defer func() {
		_, _ = io.Copy(io.Discard, resp.Body)
		_ = resp.Body.Close()
	}()
	if resp.StatusCode >= 200 && resp.StatusCode < 300 {
		d.logger.Debug("webhook delivered",
			slog.String("url", del.URL),
			slog.String("delivery_id", del.DeliveryID),
			slog.Int("status", resp.StatusCode),
		)
		return nil
	}
	if resp.StatusCode >= 500 {
		d.logger.Warn("webhook 5xx; will retry",
			slog.String("url", del.URL),
			slog.String("delivery_id", del.DeliveryID),
			slog.Int("status", resp.StatusCode),
		)
		return retryable(fmt.Errorf("webhook: receiver returned %d", resp.StatusCode))
	}
	// 4xx: receiver said "don't retry" — give up.
	d.logger.Warn("webhook 4xx; giving up",
		slog.String("url", del.URL),
		slog.String("delivery_id", del.DeliveryID),
		slog.Int("status", resp.StatusCode),
	)
	return permanent(fmt.Errorf("webhook: receiver returned %d", resp.StatusCode))
}

// retryableErr / permanentErr are the kit's local marker types so the
// retry policy can distinguish "try again" from "give up". They are
// not exported because callers should not construct them — Send maps
// HTTP/transport outcomes itself.
type retryableErr struct{ inner error }

func (e *retryableErr) Error() string { return e.inner.Error() }
func (e *retryableErr) Unwrap() error { return e.inner }

type permanentErr struct{ inner error }

func (e *permanentErr) Error() string { return e.inner.Error() }
func (e *permanentErr) Unwrap() error { return e.inner }

func retryable(err error) error { return &retryableErr{inner: err} }
func permanent(err error) error { return &permanentErr{inner: err} }

func isRetryable(err error) bool {
	if err == nil {
		return false
	}
	var perm *permanentErr
	if errors.As(err, &perm) {
		return false
	}
	var retr *retryableErr
	return errors.As(err, &retr)
}

// Compile-time check that ctx / time are referenced (the linter
// otherwise prunes the time import after refactors).
var _ = time.Now
