// asvs: V13.2.3, V3.4.1
package csrf

import (
	"crypto/hmac"
	"crypto/rand"
	"crypto/sha256"
	"crypto/subtle"
	"encoding/hex"
	"fmt"
	"io"
	"log/slog"
	"net/http"
	"net/url"
	"runtime/debug"
	"strings"
	"time"
	"unicode"
	"unicode/utf8"

	"golang.org/x/net/http/httpguts"

	coreconfig "github.com/bds421/rho-kit/core/v2/config"
	"github.com/bds421/rho-kit/core/v2/redact"
	"github.com/bds421/rho-kit/core/v2/secret"
	"github.com/bds421/rho-kit/httpx/v2"
	securitycsrf "github.com/bds421/rho-kit/security/v2/csrf"
)

const (
	// defaultCookieName is the default name for the CSRF cookie.
	defaultCookieName = "__csrf"

	// defaultHeaderName is the default name for the CSRF header.
	defaultHeaderName = "X-CSRF-Token"

	// tokenLength is the number of random bytes in a CSRF token (256 bits).
	tokenLength = 32

	// maxSignedTokenLen caps the length of a double-submit token before any
	// HMAC is computed. A well-formed token is exactly
	// hex(tokenLength) + "." + hex(sha256) = 64 + 1 + 64 = 129 chars; we allow
	// a small margin (256) and reject longer inputs up front so an attacker
	// cannot force the server to HMAC multi-MB cookie/header values on every
	// request, mirroring securitycsrf's MaxTokenLen guard.
	maxSignedTokenLen = 256

	// bearerPrefixLen is the length of the "Bearer " prefix (scheme + space).
	bearerPrefixLen = 7
)

var tokenRandReader io.Reader = rand.Reader

// Option configures the CSRF middleware.
type Option func(*config)

type config struct {
	cookieName string
	headerName string
	// secure controls Cookie.Secure on the CSRF cookie. Default
	// (when secureSet is false) is TRUE — see [New]. WithSecure
	// flips secureSet so callers can explicitly opt out for local
	// plain-HTTP development.
	secure    bool
	secureSet bool
	// secrets are HMAC keys (current first, previous verification-only
	// keys after) wrapped in [secret.String] so the raw bytes can be
	// zeroed at middleware shutdown. Reveals on the hot path happen
	// inside [secret.String.Use] closures.
	secrets          []*secret.String
	sameSite         http.SameSite
	path             string
	skipCheck        func(*http.Request) bool
	allowedOrigins   map[string]struct{}
	allowDevSecret   bool
	sessionExtractor func(*http.Request) string
	sessionTTL       time.Duration
}

// WithCookieName sets the CSRF cookie name. Default: "__csrf".
//
// Production recommendation: pass "__Host-csrf". The default config
// (Secure=true, Path="/", no Domain) already satisfies the __Host- prefix
// requirements, so a __Host- name makes browsers reject any cookie a sibling
// subdomain tries to plant — a stronger, browser-enforced defense than the
// origin allowlist alone. The default name carries no prefix semantics and
// cannot be renamed without invalidating already-deployed cookies (a v3
// candidate). When SameSite=None or Secure is disabled for local HTTP, the
// __Host- prefix will be rejected by browsers; use the plain default there.
func WithCookieName(name string) Option {
	if !httpguts.ValidHeaderFieldName(name) {
		panic("csrf: WithCookieName requires a valid cookie name")
	}
	return func(c *config) { c.cookieName = name }
}

// WithHeaderName sets the expected header name. Default: "X-CSRF-Token".
func WithHeaderName(name string) Option {
	if !httpguts.ValidHeaderFieldName(name) {
		panic("csrf: WithHeaderName requires a valid HTTP header field name")
	}
	return func(c *config) { c.headerName = name }
}

// WithoutSecureCookieForLocalHTTP opts out of the default Secure-flag
// CSRF cookie. Default middleware behaviour (no option) sets the
// Secure attribute so browsers refuse to send the cookie over
// plaintext HTTP. Pre-2.0 the default was insecure, which allowed CSRF
// cookies to ride along plaintext same-host requests (audit FR-020
// [HIGH]).
//
// Use this option ONLY for local plain-HTTP development; pair with
// [WithDevSecret] so the unsafe-default posture is explicit at the
// call site. Production deployments must never set this option.
//
// Replaces the v1 WithSecure(bool) form so the cookie-safety opt-out
// is a typed named intent rather than a one-token bool flip.
func WithoutSecureCookieForLocalHTTP() Option {
	return func(c *config) {
		c.secure = false
		c.secureSet = true
	}
}

// WithSecret sets the HMAC secret for token signing. This ensures the token
// was generated by this server, not crafted by an attacker.
//
// REQUIRED in any non-development environment (see [New]). Must be at
// least 32 bytes; passing a shorter slice panics at startup.
//
// The secret is defensively copied at construction time, so callers
// can safely zero or reuse the buffer they pass in.
func WithSecret(secret []byte) Option {
	return WithSecrets(secret)
}

// WithSecrets sets the active HMAC secret plus previous verification-only
// secrets for zero-downtime rotation. Newly issued cookies are signed with
// current. Existing cookies signed by previous secrets continue to verify until
// callers remove those secrets after the cookie/token overlap window.
//
// Panics if current or any previous secret is shorter than 32 bytes
// — HMAC-SHA256 requires at least the hash output size for its
// security guarantees. Validation runs eagerly so misconfiguration
// fails at startup, not at first request.
func WithSecrets(current []byte, previous ...[]byte) Option {
	// Validate eagerly so misconfigurations fail at startup.
	if _, err := cloneSecretRing(current, previous...); err != nil {
		panic(err.Error())
	}
	currentCopy := append([]byte(nil), current...)
	previousCopy := make([][]byte, len(previous))
	for i, p := range previous {
		previousCopy[i] = append([]byte(nil), p...)
	}
	return func(c *config) {
		// Always materialise the ring fresh per option-apply so two
		// configs do not share wrapped secret pointers (the same
		// behaviour as the pre-secret.String cloneSecretRingMust).
		s, err := cloneSecretRing(currentCopy, previousCopy...)
		if err != nil {
			panic(err.Error())
		}
		c.secrets = s
	}
}

func cloneSecretRing(current []byte, previous ...[]byte) ([]*secret.String, error) {
	if len(current) < 32 {
		return nil, fmt.Errorf("csrf: HMAC secret must be at least 32 bytes")
	}
	secrets := make([]*secret.String, 0, 1+len(previous))
	secrets = append(secrets, secret.New(current))
	for _, s := range previous {
		if len(s) < 32 {
			return nil, fmt.Errorf("csrf: HMAC secret must be at least 32 bytes")
		}
		secrets = append(secrets, secret.New(s))
	}
	return secrets, nil
}

// activeSecretBytes returns a defensive copy of the current (head) secret.
// Caller must zero the slice once done.
func activeSecretBytes(secrets []*secret.String) []byte {
	if len(secrets) == 0 || secrets[0] == nil {
		return nil
	}
	return secrets[0].Reveal()
}

// WithDevSecret opts in to per-process random secret generation. Use this
// in local development when you don't have a shared secret to inject.
// In multi-instance deployments tokens minted by pod A are rejected by
// pod B with this option, so it must NOT be used in production.
func WithDevSecret() Option {
	return func(c *config) { c.allowDevSecret = true }
}

// WithSameSite sets the SameSite attribute on the CSRF cookie.
// Default: SameSiteLaxMode.
func WithSameSite(mode http.SameSite) Option {
	switch mode {
	case http.SameSiteDefaultMode, http.SameSiteLaxMode, http.SameSiteStrictMode, http.SameSiteNoneMode:
	default:
		panic("csrf: WithSameSite requires a valid SameSite mode")
	}
	return func(c *config) { c.sameSite = mode }
}

// WithPath sets the Path attribute on the CSRF cookie. Default: "/".
func WithPath(path string) Option {
	if path == "" || !strings.HasPrefix(path, "/") {
		panic("csrf: WithPath requires an absolute cookie path")
	}
	return func(c *config) { c.path = path }
}

// WithAllowedOrigins enables Origin / Referer header validation against the
// supplied allowlist on state-changing requests. Each entry must be a full
// origin: "scheme://host[:port]" (no path, no trailing slash). Comparison
// is case-insensitive on the host.
//
// Origin/Referer validation is the second half of CSRF defense-in-depth
// alongside the double-submit cookie. It defends against three weaknesses
// of double-submit alone:
//
//   - A subdomain or sibling app on the same eTLD+1 can Set-Cookie
//     overwrite the CSRF cookie; double-submit then validates because the
//     attacker controls both halves. Origin allowlisting blocks the
//     cross-origin POST.
//   - Browsers that don't honour SameSite (older versions, atypical
//     embeds) leak cookies cross-origin.
//   - HMAC validation only proves the token was minted by *some* server
//     trusting the same secret — for multi-tenant deployments that's not
//     enough.
//
// Recommended for production deployments. Skipped for safe methods
// (GET/HEAD/OPTIONS) and for requests matched by [WithSkipCheck].
//
// When set and a state-changing request has neither Origin nor Referer, or
// has an origin outside the allowlist, the middleware returns 403 with
// "untrusted origin".
func WithAllowedOrigins(origins ...string) Option {
	// FR-021 [LOW]: parse and canonicalise origins at construction so a
	// pathful or malformed entry (https://app.example.com/, ftp://...)
	// is rejected at startup rather than failing every state-changing
	// request silently at runtime. The runtime origin normalisation
	// strips path/query/fragment, so allowlist entries that include
	// any of those would never match.
	canonical := make(map[string]struct{}, len(origins))
	for _, o := range origins {
		if strings.TrimSpace(o) == "" {
			continue
		}
		origin, err := canonicalOrigin(o, false)
		if err != nil {
			panic("csrf: WithAllowedOrigins invalid origin")
		}
		canonical[origin] = struct{}{}
	}
	if len(canonical) == 0 {
		panic("csrf: WithAllowedOrigins requires at least one non-empty origin")
	}
	return func(c *config) {
		c.allowedOrigins = make(map[string]struct{}, len(canonical))
		for origin := range canonical {
			c.allowedOrigins[origin] = struct{}{}
		}
	}
}

// WithSessionExtractor enables session-bound tokens. When set, every
// issued token is HMAC-bound to the value the extractor returns for the
// request — typically a session-cookie value or authenticated user ID
// — so a token minted for session A cannot be replayed against session B
// even if a sibling-subdomain XSS plants it via Set-Cookie.
//
// Internally, issuance and verification are delegated to
// [securitycsrf.Issuer]. The legacy double-submit-cookie path is
// disabled when this option is set.
//
// The extractor must return a non-empty string for every authenticated
// state-changing request; an empty result on a state-changing request
// causes the middleware to 403 rather than fall back to per-process
// pinning (which would defeat the purpose of session binding).
//
// An empty result on a safe method (GET/HEAD/OPTIONS) — an anonymous
// page load — passes through without a cookie, so a globally-mounted
// middleware does not 403 every unauthenticated request. An empty result
// on a state-changing request that is matched by [WithSkipCheck] (a
// bearer/API-key client with no browser session) is likewise allowed,
// honouring the skip contract. A non-empty but malformed session value is
// rejected for every method.
func WithSessionExtractor(fn func(*http.Request) string) Option {
	if fn == nil {
		panic("csrf: WithSessionExtractor requires a non-nil extractor")
	}
	return func(c *config) { c.sessionExtractor = fn }
}

// WithSessionTTL overrides the validity window for session-bound tokens.
// Default: 1 hour. Has no effect unless [WithSessionExtractor] is set.
func WithSessionTTL(d time.Duration) Option {
	if d <= 0 {
		panic("csrf: WithSessionTTL requires a positive duration")
	}
	return func(c *config) { c.sessionTTL = d }
}

// WithSkipCheck registers a predicate that bypasses CSRF validation.
// If skip returns true for a request, CSRF token validation is skipped.
// The CSRF cookie is still set (so browser clients get a token for later use),
// but the token-matching check is not enforced.
//
// Only one skip predicate is active at a time. If called multiple times,
// the last predicate wins. To combine predicates, compose them:
//
//	csrf.WithSkipCheck(func(r *http.Request) bool {
//	    return csrf.HasBearerToken(r) || csrf.HasAPIKey("X-API-Key")(r)
//	})
//
// Common use: skip CSRF for requests authenticated via Bearer tokens or API keys,
// since these auth mechanisms are not vulnerable to CSRF attacks (browsers don't
// auto-attach them in cross-origin requests).
//
// Interaction with [WithAllowedOrigins]: the origin allowlist runs BEFORE the
// skip predicate (defense-in-depth). When both options are set, a
// header-authenticated client (curl, mobile, server-to-server) that sends
// neither Origin nor Referer is still 403'd with "untrusted origin" — the very
// traffic this option is meant to admit. Such clients must send an
// allow-listed Origin or Referer, or you must not configure WithAllowedOrigins
// for those routes.
func WithSkipCheck(skip func(r *http.Request) bool) Option {
	if skip == nil {
		panic("csrf: WithSkipCheck requires a non-nil predicate")
	}
	return func(c *config) { c.skipCheck = skip }
}

// New creates a double-submit cookie CSRF middleware.
//
// On each request, if no CSRF cookie exists, one is set with a random token
// signed by the server's HMAC secret. On state-changing requests (POST, PUT,
// PATCH, DELETE), the middleware compares the cookie value with the header
// value using constant-time comparison. Safe methods (GET, HEAD, OPTIONS)
// are exempt.
//
// The frontend reads the cookie via JavaScript (HttpOnly=false) and sends
// it back as a header on mutating requests.
//
// CRITICAL: a shared HMAC secret MUST be supplied via [WithSecret].
// Without it, each pod generates a fresh random secret at startup →
// tokens minted by pod A are rejected by pod B → intermittent 403s
// after every deploy/autoscale/rotation. New panics unconditionally
// if no secret is configured. For local development with no shared
// infrastructure, use [WithDevSecret] to make the per-process random
// fallback explicit — there is no KIT_ENV escape hatch.
//
// Panics if the HMAC secret is provided but shorter than 32 bytes.
func New(opts ...Option) func(http.Handler) http.Handler {
	cfg := config{
		cookieName: defaultCookieName,
		headerName: defaultHeaderName,
		path:       "/",
	}
	sameSiteSet := false
	for _, o := range opts {
		if o == nil {
			panic("csrf: New option must not be nil")
		}
		o(&cfg)
		if cfg.sameSite != 0 {
			sameSiteSet = true
		}
	}
	if !sameSiteSet {
		// Session-bound flow defaults to Strict so a token cannot ride
		// along a cross-origin top-level navigation. Legacy double-submit
		// stays on Lax to keep forms-that-redirect working unchanged.
		if cfg.sessionExtractor != nil {
			cfg.sameSite = http.SameSiteStrictMode
		} else {
			cfg.sameSite = http.SameSiteLaxMode
		}
	}
	// FR-020 [HIGH]: default Secure to true. Pre-fix the default was
	// false, so production users that only configured the secret
	// emitted CSRF cookies without Secure and rode along plain-HTTP
	// same-host requests. WithSecure(false) is now an explicit local-
	// development opt-out (and should be paired with WithDevSecret).
	if !cfg.secureSet {
		cfg.secure = true
	}

	if len(cfg.secrets) == 0 {
		if !cfg.allowDevSecret {
			panic("csrf: New no HMAC secret configured — call WithSecret (or WithDevSecret to opt into a per-process random fallback for local development); without a shared secret, multi-instance deployments break — each pod generates a different secret and tokens minted by pod A are rejected by pod B")
		}
		raw := make([]byte, 32)
		if _, err := io.ReadFull(tokenRandReader, raw); err != nil {
			panic("csrf: New failed to generate HMAC secret")
		}
		cfg.secrets = []*secret.String{secret.New(raw)}
		// secret.New copied the bytes; wipe the local stack-allocated
		// copy so the dev-mode key has the same one-place-only memory
		// footprint as production secrets.
		for i := range raw {
			raw[i] = 0
		}
	}

	// SameSite=None requires Secure: every modern browser rejects a cookie
	// with that combination if Secure is missing, so the middleware would
	// silently fail to set the cookie at all. Catch the misconfig at startup.
	if cfg.sameSite == http.SameSiteNoneMode && !cfg.secure {
		panic("csrf: New SameSite=None requires the default Secure cookie — drop WithoutSecureCookieForLocalHTTP() when SameSite=None is set")
	}

	// Session-bound mode: build the security/csrf Issuer once and route
	// every request through it. The legacy double-submit path stays in
	// place for callers that haven't supplied an extractor.
	if cfg.sessionExtractor != nil {
		issuerOpts := []securitycsrf.Option{}
		if cfg.sessionTTL > 0 {
			issuerOpts = append(issuerOpts, securitycsrf.WithTTL(cfg.sessionTTL))
		}
		// Reveal the wrapped secrets only for the duration of Issuer
		// construction. The Issuer keeps its own copy of the bytes so
		// the locals zero cleanly afterwards.
		current := activeSecretBytes(cfg.secrets)
		previous := make([][]byte, 0, len(cfg.secrets)-1)
		for _, s := range cfg.secrets[1:] {
			previous = append(previous, s.Reveal())
		}
		issuer := securitycsrf.MustNewIssuerWithSecrets(current, previous, issuerOpts...)
		currentIssuer := securitycsrf.MustNewIssuer(current, issuerOpts...)
		for i := range current {
			current[i] = 0
		}
		for _, p := range previous {
			for i := range p {
				p[i] = 0
			}
		}
		return sessionBoundMiddleware(&cfg, issuer, currentIssuer)
	}

	return func(next http.Handler) http.Handler {
		return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
			// Ensure a CSRF cookie exists on every response.
			cookie, err := r.Cookie(cfg.cookieName)
			cookieRegenerated := false
			if err != nil || !isValidSignedTokenAny(cookie.Value, cfg.secrets) {
				// Generate a new token and set it as a cookie.
				token, err := mintSignedToken(cfg.secrets[0])
				if err != nil {
					httpx.WriteError(w, http.StatusInternalServerError, "csrf: token mint failed")
					return
				}
				http.SetCookie(w, &http.Cookie{
					Name:     cfg.cookieName,
					Value:    token,
					Path:     cfg.path,
					MaxAge:   86400, // 24h — bounds token lifetime for rotation
					HttpOnly: false, // Must be readable by JavaScript
					Secure:   cfg.secure,
					SameSite: cfg.sameSite,
				})
				// The local cookie ref must reflect the freshly-issued
				// token; otherwise the validation block below compares
				// against the stale invalid cookie and 403s the same
				// request that just received a new cookie.
				cookie = &http.Cookie{Name: cfg.cookieName, Value: token}
				cookieRegenerated = true
			} else if !isValidSignedToken(cookie.Value, cfg.secrets[0]) {
				// Previous-secret token accepted during rotation. Reissue a
				// current-secret cookie for the next request, but keep the
				// incoming cookie as the value to compare against this request's
				// header.
				token, err := mintSignedToken(cfg.secrets[0])
				if err != nil {
					httpx.WriteError(w, http.StatusInternalServerError, "csrf: token mint failed")
					return
				}
				http.SetCookie(w, &http.Cookie{
					Name:     cfg.cookieName,
					Value:    token,
					Path:     cfg.path,
					MaxAge:   86400,
					HttpOnly: false,
					Secure:   cfg.secure,
					SameSite: cfg.sameSite,
				})
			}

			// Safe methods are exempt from CSRF validation.
			switch r.Method {
			case http.MethodGet, http.MethodHead, http.MethodOptions:
				next.ServeHTTP(w, r)
				return
			}

			// Origin/Referer validation runs BEFORE the skip-check
			// predicate. Defense-in-depth: a consumer that uses both
			// WithSkipCheck(HasBearerToken) and WithAllowedOrigins(...)
			// expects bearer-token requests to skip the cookie match
			// AND unfamiliar-origin POSTs to be rejected. Reordering
			// the skip-check ahead of the origin check would let a
			// bearer-bearing POST from any origin pass — defeating the
			// allowlist for the very class of caller most likely to
			// be impersonated by an attacker who phished a token.
			if len(cfg.allowedOrigins) > 0 {
				if !originAllowed(r, cfg.allowedOrigins) {
					httpx.WriteError(w, http.StatusForbidden, "untrusted origin")
					return
				}
			}

			// If the skip predicate matches, bypass CSRF token validation.
			// The cookie was already set above, so browser clients still
			// receive a token for later use.
			if cfg.skipCheck != nil && safeSkipCheck(cfg.skipCheck, r) {
				next.ServeHTTP(w, r)
				return
			}

			// State-changing methods require a valid CSRF token. If the
			// cookie was regenerated above (incoming was missing or
			// tampered), short-circuit with a clear 403: the client
			// has only just received the new cookie in this response,
			// so its current request necessarily can't have matched it.
			if cookieRegenerated {
				httpx.WriteError(w, http.StatusForbidden, "CSRF cookie was reissued; retry with the new cookie")
				return
			}
			// Invariant: cookieRegenerated is false here, so the regeneration
			// branch at the top of the handler (cookie missing OR token
			// invalid) was NOT taken — cookie is therefore non-nil, err is
			// nil, and the token already passed isValidSignedTokenAny. Only
			// the degenerate empty value needs a defensive reject.
			if cookie.Value == "" {
				httpx.WriteError(w, http.StatusForbidden, "missing CSRF cookie")
				return
			}

			headerToken, present, ok := strictSingleHeaderValue(r.Header, cfg.headerName)
			if !present {
				httpx.WriteError(w, http.StatusForbidden, "missing CSRF header")
				return
			}
			if !ok {
				httpx.WriteError(w, http.StatusForbidden, "invalid CSRF header")
				return
			}

			// Constant-time comparison of cookie and header values.
			if subtle.ConstantTimeCompare([]byte(cookie.Value), []byte(headerToken)) != 1 {
				httpx.WriteError(w, http.StatusForbidden, "CSRF token mismatch")
				return
			}

			// Verify the token was signed by this server.
			if !isValidSignedTokenAny(headerToken, cfg.secrets) {
				httpx.WriteError(w, http.StatusForbidden, "invalid CSRF token")
				return
			}

			next.ServeHTTP(w, r)
		})
	}
}

// sessionBoundMiddleware is the session-bound flow: tokens are minted
// and verified by [securitycsrf.Issuer] so cross-session replay is
// rejected even when the cookie itself is intact.
func sessionBoundMiddleware(cfg *config, issuer, currentIssuer *securitycsrf.Issuer) func(http.Handler) http.Handler {
	// Align the cookie lifetime with the session token's validity window so a
	// browser does not hold a dead cookie long after the token expires (which
	// would force a deterministic 403+reissue+retry on the first request after
	// an idle period). Derive MaxAge from the effective TTL (configured or the
	// security/csrf default) rather than a hardcoded 24h.
	effectiveTTL := cfg.sessionTTL
	if effectiveTTL <= 0 {
		effectiveTTL = securitycsrf.DefaultTTL
	}
	cookieMaxAge := int(effectiveTTL.Seconds())
	return func(next http.Handler) http.Handler {
		return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
			session, ok := safeSessionExtractor(cfg.sessionExtractor, r)
			if !ok {
				// The extractor panicked — fail closed rather than guess
				// at an anonymous-vs-authenticated state.
				httpx.WriteError(w, http.StatusForbidden, "csrf: session required")
				return
			}
			if session == "" {
				// Anonymous request: there is no session to bind a token
				// to, so no cookie is issued. The session requirement is
				// scoped (per WithSessionExtractor docs) to authenticated
				// state-changing requests; safe methods and skip-matched
				// requests must still pass so a globally-mounted middleware
				// does not 403 every anonymous page load or break the
				// documented WithSkipCheck bearer/API-key contract.
				handleAnonymousSessionBound(cfg, next, w, r)
				return
			}
			if securitycsrf.ValidateSessionID(session) != nil {
				// A session value is present but malformed (control chars,
				// over-length, …): treat as a security signal and reject
				// before issuing a cookie, for every method.
				httpx.WriteError(w, http.StatusForbidden, "csrf: session required")
				return
			}

			// Issue a fresh token cookie when the request lacks one OR
			// the existing cookie no longer verifies under the current
			// session (logout/login swap, expired token).
			cookie, err := r.Cookie(cfg.cookieName)
			cookieRegenerated := false
			if err != nil || issuer.Verify(securitycsrf.Token(cookie.Value), session) != nil {
				token, mintErr := issuer.Issue(session)
				if mintErr != nil {
					httpx.WriteError(w, http.StatusInternalServerError, "csrf: token mint failed")
					return
				}
				http.SetCookie(w, &http.Cookie{
					Name:     cfg.cookieName,
					Value:    string(token),
					Path:     cfg.path,
					MaxAge:   cookieMaxAge,
					HttpOnly: false,
					Secure:   cfg.secure,
					SameSite: cfg.sameSite,
				})
				cookie = &http.Cookie{Name: cfg.cookieName, Value: string(token)}
				cookieRegenerated = true
			} else if currentIssuer.Verify(securitycsrf.Token(cookie.Value), session) != nil {
				token, mintErr := issuer.Issue(session)
				if mintErr != nil {
					httpx.WriteError(w, http.StatusInternalServerError, "csrf: token mint failed")
					return
				}
				http.SetCookie(w, &http.Cookie{
					Name:     cfg.cookieName,
					Value:    string(token),
					Path:     cfg.path,
					MaxAge:   cookieMaxAge,
					HttpOnly: false,
					Secure:   cfg.secure,
					SameSite: cfg.sameSite,
				})
			}

			switch r.Method {
			case http.MethodGet, http.MethodHead, http.MethodOptions:
				next.ServeHTTP(w, r)
				return
			}

			// Origin allowlist runs BEFORE the skip-check predicate
			// for the same defense-in-depth reasoning as the
			// double-submit flow above.
			if len(cfg.allowedOrigins) > 0 && !originAllowed(r, cfg.allowedOrigins) {
				httpx.WriteError(w, http.StatusForbidden, "untrusted origin")
				return
			}

			if cfg.skipCheck != nil && safeSkipCheck(cfg.skipCheck, r) {
				next.ServeHTTP(w, r)
				return
			}

			if cookieRegenerated {
				httpx.WriteError(w, http.StatusForbidden, "CSRF cookie was reissued; retry with the new cookie")
				return
			}

			headerToken, present, ok := strictSingleHeaderValue(r.Header, cfg.headerName)
			if !present {
				httpx.WriteError(w, http.StatusForbidden, "missing CSRF header")
				return
			}
			if !ok {
				httpx.WriteError(w, http.StatusForbidden, "invalid CSRF header")
				return
			}
			if subtle.ConstantTimeCompare([]byte(cookie.Value), []byte(headerToken)) != 1 {
				httpx.WriteError(w, http.StatusForbidden, "CSRF token mismatch")
				return
			}
			if err := issuer.Verify(securitycsrf.Token(headerToken), session); err != nil {
				httpx.WriteError(w, http.StatusForbidden, "invalid CSRF token")
				return
			}

			next.ServeHTTP(w, r)
		})
	}
}

// handleAnonymousSessionBound serves a request whose session extractor
// returned the empty string (an unauthenticated caller). No token cookie
// can be bound without a session, so none is issued. Safe methods pass
// through, and state-changing requests honour the origin allowlist and the
// skip predicate (same ordering as the authenticated path) before the
// session-required gate finally rejects mutating requests.
func handleAnonymousSessionBound(cfg *config, next http.Handler, w http.ResponseWriter, r *http.Request) {
	switch r.Method {
	case http.MethodGet, http.MethodHead, http.MethodOptions:
		next.ServeHTTP(w, r)
		return
	}

	// Origin allowlist runs BEFORE the skip-check predicate for the same
	// defense-in-depth reasoning as the authenticated path above.
	if len(cfg.allowedOrigins) > 0 && !originAllowed(r, cfg.allowedOrigins) {
		httpx.WriteError(w, http.StatusForbidden, "untrusted origin")
		return
	}

	if cfg.skipCheck != nil && safeSkipCheck(cfg.skipCheck, r) {
		next.ServeHTTP(w, r)
		return
	}

	// A state-changing request without a session is rejected rather than
	// falling back to per-process pinning, which would defeat the purpose
	// of session binding.
	httpx.WriteError(w, http.StatusForbidden, "csrf: session required")
}

func safeSkipCheck(skip func(*http.Request) bool, r *http.Request) (matched bool) {
	defer func() {
		if rec := recover(); rec != nil {
			slog.Default().Error("csrf: skip predicate panicked",
				redact.Panic(rec),
				"stack", string(debug.Stack()),
			)
			matched = false
		}
	}()
	return skip(r)
}

func safeSessionExtractor(extract func(*http.Request) string, r *http.Request) (session string, ok bool) {
	defer func() {
		if rec := recover(); rec != nil {
			slog.Default().Error("csrf: session extractor panicked",
				redact.Panic(rec),
				"stack", string(debug.Stack()),
			)
			session, ok = "", false
		}
	}()
	return extract(r), true
}

// originAllowed inspects Origin then Referer (in that order) and reports
// whether the request's origin appears in the allowlist. A request with
// neither header is rejected — modern browsers always send Origin on
// state-changing cross-origin requests, so the absence is itself
// suspicious in the contexts where Origin checks matter.
func originAllowed(r *http.Request, allow map[string]struct{}) bool {
	raw, present, ok := singleHeaderValue(r.Header, "Origin")
	if present {
		if !ok || raw == "null" {
			return false
		}
		return rawOriginAllowed(raw, allow)
	}

	raw, present, ok = singleHeaderValue(r.Header, "Referer")
	if !present || !ok || raw == "null" {
		return false
	}
	return rawOriginAllowed(raw, allow)
}

func rawOriginAllowed(raw string, allow map[string]struct{}) bool {
	o, err := canonicalOrigin(raw, true)
	if err != nil {
		return false
	}
	_, ok := allow[o]
	return ok
}

func singleHeaderValue(h http.Header, name string) (value string, present bool, ok bool) {
	values := h.Values(name)
	if len(values) == 0 {
		return "", false, true
	}
	if len(values) != 1 {
		return "", true, false
	}
	raw := values[0]
	if raw == "" || !utf8.ValidString(raw) || !httpguts.ValidHeaderFieldValue(raw) {
		return "", true, false
	}
	value = strings.TrimSpace(raw)
	if value == "" {
		return "", true, false
	}
	return value, true, true
}

func strictSingleHeaderValue(h http.Header, name string) (value string, present bool, ok bool) {
	values := h.Values(name)
	if len(values) == 0 {
		return "", false, true
	}
	if len(values) != 1 {
		return "", true, false
	}
	value = values[0]
	if value == "" || strings.TrimSpace(value) != value || !utf8.ValidString(value) || !httpguts.ValidHeaderFieldValue(value) || strings.Contains(value, ",") {
		return "", true, false
	}
	for _, r := range value {
		if unicode.IsSpace(r) || unicode.IsControl(r) {
			return "", true, false
		}
	}
	return value, true, true
}

// canonicalOrigin extracts "scheme://host[:port]" from an Origin or Referer
// header value, lower-casing the host so comparison is case-insensitive.
func canonicalOrigin(raw string, allowPath bool) (string, error) {
	raw = strings.TrimSpace(raw)
	if raw == "" || raw == "null" {
		return "", fmt.Errorf("empty or null origin")
	}
	u, err := url.Parse(raw)
	if err != nil {
		return "", fmt.Errorf("origin URL is invalid")
	}
	switch strings.ToLower(u.Scheme) {
	case "http", "https":
	default:
		return "", fmt.Errorf("scheme must be http or https")
	}
	if u.User != nil {
		return "", fmt.Errorf("origin must not include userinfo")
	}
	if !allowPath && (u.Path != "" || u.RawQuery != "" || u.Fragment != "") {
		return "", fmt.Errorf("origin must not include path, query, or fragment")
	}
	if err := coreconfig.ValidateURLHost("csrf origin", u); err != nil {
		return "", err
	}
	return strings.ToLower(u.Scheme + "://" + u.Host), nil
}

// mintSignedToken creates a random token with an HMAC signature.
// Format: "<random_hex>.<hmac_hex>". The middleware handler converts a
// crypto/rand failure into HTTP 500 rather than crashing the request goroutine.
func mintSignedToken(s *secret.String) (string, error) {
	raw := make([]byte, tokenLength)
	if _, err := io.ReadFull(tokenRandReader, raw); err != nil {
		return "", fmt.Errorf("csrf: generate random token: %w", err)
	}
	tokenHex := hex.EncodeToString(raw)
	sig := computeHMACWithSecret(tokenHex, s)
	return tokenHex + "." + sig, nil
}

// isValidSignedToken verifies that the token was signed by the server.
func isValidSignedToken(token string, s *secret.String) bool {
	// Reject over-length tokens before computing any HMAC so a hostile
	// multi-MB cookie/header value cannot turn every request into an
	// attacker-controlled SHA-256 over megabytes of input.
	if len(token) > maxSignedTokenLen {
		return false
	}
	parts := strings.SplitN(token, ".", 2)
	if len(parts) != 2 || parts[0] == "" || parts[1] == "" {
		return false
	}
	expectedSig := computeHMACWithSecret(parts[0], s)
	return hmac.Equal([]byte(parts[1]), []byte(expectedSig))
}

func isValidSignedTokenAny(token string, secrets []*secret.String) bool {
	valid := false
	for _, s := range secrets {
		if isValidSignedToken(token, s) {
			valid = true
		}
	}
	return valid
}

// computeHMACWithSecret reveals the wrapped key inside a [secret.String.Use]
// closure so the bytes have lifetime bounded to the HMAC compute.
func computeHMACWithSecret(data string, s *secret.String) string {
	var sum []byte
	s.Use(func(k []byte) {
		mac := hmac.New(sha256.New, k)
		mac.Write([]byte(data))
		sum = mac.Sum(nil)
	})
	return hex.EncodeToString(sum)
}

// HasBearerToken returns true if the request has an Authorization header
// with a Bearer token. The "Bearer " prefix check is case-insensitive per
// RFC 6750 (auth-scheme comparison is case-insensitive).
// Bearer-authenticated requests are immune to CSRF because browsers never
// auto-attach the Authorization header in cross-origin requests.
func HasBearerToken(r *http.Request) bool {
	if r == nil {
		return false
	}
	values := r.Header.Values("Authorization")
	if len(values) != 1 {
		return false
	}
	v := values[0]
	if v == "" || strings.TrimSpace(v) != v || !utf8.ValidString(v) || !httpguts.ValidHeaderFieldValue(v) {
		return false
	}
	if len(v) <= bearerPrefixLen || !strings.EqualFold(v[:bearerPrefixLen], "bearer ") {
		return false
	}
	token := v[bearerPrefixLen:]
	if token == "" || strings.TrimSpace(token) != token || strings.Contains(token, ",") {
		return false
	}
	for _, r := range token {
		if unicode.IsSpace(r) || unicode.IsControl(r) {
			return false
		}
	}
	return true
}

// HasAPIKey returns a predicate that checks for the presence of a non-empty
// API key header. The header name is configurable (e.g., "X-API-Key",
// "X-Api-Token"). Like Bearer tokens, custom API key headers are not
// auto-attached by browsers.
//
// Panics if header is invalid.
func HasAPIKey(header string) func(r *http.Request) bool {
	if !httpguts.ValidHeaderFieldName(header) {
		panic("csrf: HasAPIKey header name must be a valid non-empty HTTP header field name")
	}
	return func(r *http.Request) bool {
		if r == nil {
			return false
		}
		_, present, ok := strictSingleHeaderValue(r.Header, header)
		return present && ok
	}
}

// RequireJSONContentType rejects state-changing requests that carry a body
// without a JSON Content-Type. Requests without a body
// (ContentLength == 0 and Body is nil or http.NoBody) are allowed through
// regardless of Content-Type — this supports body-less actions like
// POST /restart.
func RequireJSONContentType(next http.Handler) http.Handler {
	return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.Method {
		case http.MethodPost, http.MethodPut, http.MethodPatch, http.MethodDelete:
			contentType, present, ok := singleHeaderValue(r.Header, "Content-Type")
			if hasBody(r) && (!present || !ok || !httpx.IsJSONContentType(contentType)) {
				httpx.WriteError(w, http.StatusUnsupportedMediaType, "Content-Type must be application/json")
				return
			}
		}
		next.ServeHTTP(w, r)
	})
}

// hasBody reports whether the request appears to carry a body.
func hasBody(r *http.Request) bool {
	return r.ContentLength > 0 || (r.ContentLength < 0 && r.Body != nil && r.Body != http.NoBody)
}
