package csrf

import (
	"crypto/hmac"
	"crypto/rand"
	"crypto/sha256"
	"crypto/subtle"
	"encoding/hex"
	"mime"
	"net/http"
	"strings"

	"github.com/bds421/rho-kit/httpx"
)

const (
	// defaultCookieName is the default name for the CSRF cookie.
	defaultCookieName = "__csrf"

	// defaultHeaderName is the default name for the CSRF header.
	defaultHeaderName = "X-CSRF-Token"

	// tokenLength is the number of random bytes in a CSRF token (256 bits).
	tokenLength = 32
)

// Option configures the CSRF middleware.
type Option func(*config)

type config struct {
	cookieName string
	headerName string
	secure     bool
	secret     []byte // HMAC key for token signing
	sameSite   http.SameSite
	path       string
	skipCheck  func(*http.Request) bool
}

// WithCookieName sets the CSRF cookie name. Default: "__csrf".
func WithCookieName(name string) Option {
	return func(c *config) { c.cookieName = name }
}

// WithHeaderName sets the expected header name. Default: "X-CSRF-Token".
func WithHeaderName(name string) Option {
	return func(c *config) { c.headerName = name }
}

// WithSecure sets the Secure flag on the CSRF cookie. Default: false.
// Set to true in production (HTTPS).
func WithSecure(secure bool) Option {
	return func(c *config) { c.secure = secure }
}

// WithSecret sets the HMAC secret for token signing. This ensures the token
// was generated by this server, not crafted by an attacker. When nil (default),
// a random 32-byte key is generated at startup.
func WithSecret(secret []byte) Option {
	return func(c *config) { c.secret = secret }
}

// WithSameSite sets the SameSite attribute on the CSRF cookie.
// Default: SameSiteLaxMode.
func WithSameSite(mode http.SameSite) Option {
	return func(c *config) { c.sameSite = mode }
}

// WithPath sets the Path attribute on the CSRF cookie. Default: "/".
func WithPath(path string) Option {
	return func(c *config) { c.path = path }
}

// WithSkipCheck registers a predicate that bypasses CSRF validation.
// If skip returns true for a request, CSRF token validation is skipped.
// The CSRF cookie is still set (so browser clients get a token for later use),
// but the token-matching check is not enforced.
//
// Only one skip predicate is active at a time. If called multiple times,
// the last predicate wins. To combine predicates, compose them:
//
//	csrf.WithSkipCheck(func(r *http.Request) bool {
//	    return csrf.HasBearerToken(r) || csrf.HasAPIKey("X-API-Key")(r)
//	})
//
// Common use: skip CSRF for requests authenticated via Bearer tokens or API keys,
// since these auth mechanisms are not vulnerable to CSRF attacks (browsers don't
// auto-attach them in cross-origin requests).
func WithSkipCheck(skip func(r *http.Request) bool) Option {
	return func(c *config) { c.skipCheck = skip }
}

// New creates a double-submit cookie CSRF middleware.
//
// On each request, if no CSRF cookie exists, one is set with a random token
// signed by the server's HMAC secret. On state-changing requests (POST, PUT,
// PATCH, DELETE), the middleware compares the cookie value with the header
// value using constant-time comparison. Safe methods (GET, HEAD, OPTIONS)
// are exempt.
//
// The frontend reads the cookie via JavaScript (HttpOnly=false) and sends
// it back as a header on mutating requests.
//
// Panics if the HMAC secret is provided but shorter than 32 bytes.
func New(opts ...Option) func(http.Handler) http.Handler {
	cfg := config{
		cookieName: defaultCookieName,
		headerName: defaultHeaderName,
		sameSite:   http.SameSiteLaxMode,
		path:       "/",
	}
	for _, o := range opts {
		o(&cfg)
	}

	if cfg.secret == nil {
		cfg.secret = make([]byte, 32)
		if _, err := rand.Read(cfg.secret); err != nil {
			panic("csrf: failed to generate HMAC secret: " + err.Error())
		}
	} else if len(cfg.secret) < 32 {
		panic("csrf: HMAC secret must be at least 32 bytes")
	}

	return func(next http.Handler) http.Handler {
		return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
			// Ensure a CSRF cookie exists on every response.
			cookie, err := r.Cookie(cfg.cookieName)
			if err != nil || !isValidSignedToken(cookie.Value, cfg.secret) {
				// Generate a new token and set it as a cookie.
				token := generateSignedToken(cfg.secret)
				http.SetCookie(w, &http.Cookie{
					Name:     cfg.cookieName,
					Value:    token,
					Path:     cfg.path,
					MaxAge:   86400, // 24h — bounds token lifetime for rotation
					HttpOnly: false, // Must be readable by JavaScript
					Secure:   cfg.secure,
					SameSite: cfg.sameSite,
				})
			}

			// Safe methods are exempt from CSRF validation.
			switch r.Method {
			case http.MethodGet, http.MethodHead, http.MethodOptions:
				next.ServeHTTP(w, r)
				return
			}

			// If the skip predicate matches, bypass CSRF token validation.
			// The cookie was already set above, so browser clients still
			// receive a token for later use.
			if cfg.skipCheck != nil && cfg.skipCheck(r) {
				next.ServeHTTP(w, r)
				return
			}

			// State-changing methods require a valid CSRF token.
			if cookie == nil {
				cookie, err = r.Cookie(cfg.cookieName)
			}
			if err != nil || cookie.Value == "" {
				httpx.WriteError(w, http.StatusForbidden, "missing CSRF cookie")
				return
			}

			headerToken := r.Header.Get(cfg.headerName)
			if headerToken == "" {
				httpx.WriteError(w, http.StatusForbidden, "missing "+cfg.headerName+" header")
				return
			}

			// Constant-time comparison of cookie and header values.
			if subtle.ConstantTimeCompare([]byte(cookie.Value), []byte(headerToken)) != 1 {
				httpx.WriteError(w, http.StatusForbidden, "CSRF token mismatch")
				return
			}

			// Verify the token was signed by this server.
			if !isValidSignedToken(headerToken, cfg.secret) {
				httpx.WriteError(w, http.StatusForbidden, "invalid CSRF token")
				return
			}

			next.ServeHTTP(w, r)
		})
	}
}

// generateSignedToken creates a random token with an HMAC signature.
// Format: "<random_hex>.<hmac_hex>"
func generateSignedToken(secret []byte) string {
	raw := make([]byte, tokenLength)
	if _, err := rand.Read(raw); err != nil {
		panic("csrf: failed to generate random token: " + err.Error())
	}
	tokenHex := hex.EncodeToString(raw)
	sig := computeHMAC(tokenHex, secret)
	return tokenHex + "." + sig
}

// isValidSignedToken verifies that the token was signed by the server.
func isValidSignedToken(token string, secret []byte) bool {
	parts := strings.SplitN(token, ".", 2)
	if len(parts) != 2 || parts[0] == "" || parts[1] == "" {
		return false
	}
	expectedSig := computeHMAC(parts[0], secret)
	return hmac.Equal([]byte(parts[1]), []byte(expectedSig))
}

// computeHMAC returns the hex-encoded HMAC-SHA256 of data using the given key.
func computeHMAC(data string, key []byte) string {
	mac := hmac.New(sha256.New, key)
	mac.Write([]byte(data))
	return hex.EncodeToString(mac.Sum(nil))
}

// HasBearerToken returns true if the request has an Authorization header
// with a Bearer token. The "Bearer " prefix check is case-insensitive per
// RFC 6750 (auth-scheme comparison is case-insensitive).
// Bearer-authenticated requests are immune to CSRF because browsers never
// auto-attach the Authorization header in cross-origin requests.
func HasBearerToken(r *http.Request) bool {
	v := r.Header.Get("Authorization")
	return len(v) > 7 && strings.EqualFold(v[:7], "bearer ")
}

// HasAPIKey returns a predicate that checks for the presence of a non-empty
// API key header. The header name is configurable (e.g., "X-API-Key",
// "X-Api-Token"). Like Bearer tokens, custom API key headers are not
// auto-attached by browsers.
//
// Panics if header is empty.
func HasAPIKey(header string) func(r *http.Request) bool {
	if header == "" {
		panic("csrf: HasAPIKey header name must not be empty")
	}
	return func(r *http.Request) bool {
		return r.Header.Get(header) != ""
	}
}

// RequireCSRF rejects state-changing requests (POST, PUT, PATCH, DELETE) that
// don't include the X-Requested-With header. Since custom headers can't be set
// by cross-origin HTML forms, this prevents CSRF attacks on cookie-based auth.
// GET/HEAD/OPTIONS requests are exempt.
//
// Deprecated: Use [New] for proper double-submit cookie CSRF protection.
// This function only checks header presence, not a cryptographic token.
// It is retained for backward compatibility but should not be used for
// new code.
func RequireCSRF(next http.Handler) http.Handler {
	return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.Method {
		case http.MethodPost, http.MethodPut, http.MethodPatch, http.MethodDelete:
			if r.Header.Get("X-Requested-With") == "" {
				httpx.WriteError(w, http.StatusForbidden, "missing X-Requested-With header")
				return
			}
		}
		next.ServeHTTP(w, r)
	})
}

// RequireJSONContentType rejects state-changing requests that carry a body
// without an application/json Content-Type.
func RequireJSONContentType(next http.Handler) http.Handler {
	return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.Method {
		case http.MethodPost, http.MethodPut, http.MethodPatch:
			if !isJSONContentType(r.Header.Get("Content-Type")) {
				httpx.WriteError(w, http.StatusUnsupportedMediaType, "Content-Type must be application/json")
				return
			}
		case http.MethodDelete:
			// ContentLength is -1 for chunked/unknown bodies. Check Content-Type
			// header presence instead — a DELETE with no body has no Content-Type.
			ct := r.Header.Get("Content-Type")
			if ct != "" && !isJSONContentType(ct) {
				httpx.WriteError(w, http.StatusUnsupportedMediaType, "Content-Type must be application/json")
				return
			}
		}
		next.ServeHTTP(w, r)
	})
}

// isJSONContentType returns true if the Content-Type is application/json.
func isJSONContentType(value string) bool {
	if value == "" {
		return false
	}
	mediaType, _, err := mime.ParseMediaType(value)
	if err != nil {
		return false
	}
	return strings.EqualFold(mediaType, "application/json")
}
